// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0RGdo1t_qCQ-KiXXzBK60C3NK-iZSgA',
    appId: '1:865405146271:web:32e4636fa9e6995538beaa',
    messagingSenderId: '865405146271',
    projectId: 'wasla-25109',
    authDomain: 'wasla-25109.firebaseapp.com',
    storageBucket: 'wasla-25109.firebasestorage.app',
    measurementId: 'G-665J24XFE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Vt-E6YbKY__yrZadNKAR20OrRL7Ph_A',
    appId: '1:865405146271:android:fe80662dcacd4e9938beaa',
    messagingSenderId: '865405146271',
    projectId: 'wasla-25109',
    storageBucket: 'wasla-25109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTx6Bq1h4MsMA--SyCh9fJ9Clu5KyIW4A',
    appId: '1:865405146271:ios:9c23838eb238aaaa38beaa',
    messagingSenderId: '865405146271',
    projectId: 'wasla-25109',
    storageBucket: 'wasla-25109.firebasestorage.app',
    iosBundleId: 'com.example.wasla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTx6Bq1h4MsMA--SyCh9fJ9Clu5KyIW4A',
    appId: '1:865405146271:ios:9c23838eb238aaaa38beaa',
    messagingSenderId: '865405146271',
    projectId: 'wasla-25109',
    storageBucket: 'wasla-25109.firebasestorage.app',
    iosBundleId: 'com.example.wasla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF0RGdo1t_qCQ-KiXXzBK60C3NK-iZSgA',
    appId: '1:865405146271:web:9ceb5410a8f93bce38beaa',
    messagingSenderId: '865405146271',
    projectId: 'wasla-25109',
    authDomain: 'wasla-25109.firebaseapp.com',
    storageBucket: 'wasla-25109.firebasestorage.app',
    measurementId: 'G-EHEVZYYC1L',
  );
}
